-- Shop2Door — AWS RDS for SQL Server schema.
-- Run once against the RDS database. The backend serves identical seed data
-- only when the application is running outside production.

CREATE TABLE users (
  id NVARCHAR(32) PRIMARY KEY,
  name NVARCHAR(120) NOT NULL,
  email NVARCHAR(160) NOT NULL UNIQUE,
  mobile NVARCHAR(40) NOT NULL DEFAULT '',
  role NVARCHAR(20) NOT NULL DEFAULT 'user',
  passwordHash NVARCHAR(128) NULL,
  salt NVARCHAR(64) NULL,
  memberSince NVARCHAR(40) NOT NULL DEFAULT '',
  walletBalance INT NOT NULL DEFAULT 0,
  walletPromo INT NOT NULL DEFAULT 0,
  walletRefund INT NOT NULL DEFAULT 0,
  walletSaved INT NOT NULL DEFAULT 0,
  loyaltyTier NVARCHAR(20) NOT NULL DEFAULT 'Bronze',
  loyaltyPoints INT NOT NULL DEFAULT 0,
  providerId NVARCHAR(32) NULL
);

CREATE TABLE categories (
  [key] NVARCHAR(40) PRIMARY KEY,
  label NVARCHAR(60) NOT NULL,
  icon NVARCHAR(10) NOT NULL DEFAULT '',
  tone NVARCHAR(40) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0
);

CREATE TABLE providers (
  id NVARCHAR(32) PRIMARY KEY,
  name NVARCHAR(160) NOT NULL,
  category NVARCHAR(80) NOT NULL DEFAULT '',
  categoryKey NVARCHAR(40) NOT NULL DEFAULT '',
  exp NVARCHAR(80) NOT NULL DEFAULT '',
  expYears INT NOT NULL DEFAULT 0,
  rating FLOAT NOT NULL DEFAULT 5,
  reviewsCount INT NOT NULL DEFAULT 0,
  responseMin INT NOT NULL DEFAULT 15,
  distanceKm FLOAT NOT NULL DEFAULT 1,
  priceFrom INT NOT NULL DEFAULT 0,
  priceUnit NVARCHAR(10) NOT NULL DEFAULT '',
  tags NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  initials NVARCHAR(8) NOT NULL DEFAULT '',
  verified BIT NOT NULL DEFAULT 0,
  available BIT NOT NULL DEFAULT 1,
  area NVARCHAR(200) NOT NULL DEFAULT '',
  about NVARCHAR(MAX) NOT NULL DEFAULT '',
  trust NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  slots NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  verification NVARCHAR(20) NOT NULL DEFAULT 'Pending',
  status NVARCHAR(20) NOT NULL DEFAULT 'Review',
  availability NVARCHAR(20) NOT NULL DEFAULT 'Unavailable',
  jobsCompleted INT NOT NULL DEFAULT 0
);

CREATE TABLE services (
  id NVARCHAR(32) PRIMARY KEY,
  providerId NVARCHAR(32) NOT NULL,
  name NVARCHAR(160) NOT NULL,
  detail NVARCHAR(250) NOT NULL DEFAULT '',
  price INT NOT NULL DEFAULT 0,
  durationMin INT NOT NULL DEFAULT 30,
  active BIT NOT NULL DEFAULT 1
);
CREATE INDEX IX_services_provider ON services(providerId);

CREATE TABLE reviews (
  id NVARCHAR(32) PRIMARY KEY,
  providerId NVARCHAR(32) NOT NULL,
  author NVARCHAR(120) NOT NULL DEFAULT '',
  rating INT NOT NULL DEFAULT 5,
  text NVARCHAR(MAX) NOT NULL DEFAULT '',
  tags NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  at NVARCHAR(40) NOT NULL DEFAULT ''
);
CREATE INDEX IX_reviews_provider ON reviews(providerId);

CREATE TABLE bookings (
  id NVARCHAR(32) PRIMARY KEY,
  code NVARCHAR(40) NOT NULL,
  userId NVARCHAR(32) NOT NULL,
  customerName NVARCHAR(120) NOT NULL DEFAULT '',
  providerId NVARCHAR(32) NOT NULL,
  partnerName NVARCHAR(160) NOT NULL DEFAULT '',
  serviceId NVARCHAR(32) NOT NULL DEFAULT '',
  serviceName NVARCHAR(160) NOT NULL DEFAULT '',
  monthLabel NVARCHAR(10) NOT NULL DEFAULT '',
  dayNum NVARCHAR(10) NOT NULL DEFAULT '',
  dateLabel NVARCHAR(80) NOT NULL DEFAULT '',
  dateValue NVARCHAR(20) NULL,
  timeLabel NVARCHAR(40) NOT NULL DEFAULT '',
  address NVARCHAR(250) NOT NULL DEFAULT '',
  comments NVARCHAR(500) NOT NULL DEFAULT '',
  price INT NOT NULL DEFAULT 0,
  fee INT NOT NULL DEFAULT 0,
  gst INT NOT NULL DEFAULT 0,
  amount INT NOT NULL DEFAULT 0,
  status NVARCHAR(20) NOT NULL DEFAULT 'pending',
  payment NVARCHAR(20) NOT NULL DEFAULT 'UPI',
  createdAt NVARCHAR(60) NOT NULL DEFAULT '',
  history NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  reviewed BIT NOT NULL DEFAULT 0
);
CREATE INDEX IX_bookings_user ON bookings(userId);

CREATE TABLE wallet_txns (
  row INT IDENTITY(1,1) PRIMARY KEY,
  id NVARCHAR(32) NOT NULL,
  userId NVARCHAR(32) NOT NULL,
  name NVARCHAR(160) NOT NULL DEFAULT '',
  meta NVARCHAR(250) NOT NULL DEFAULT '',
  amount INT NOT NULL DEFAULT 0,
  kind NVARCHAR(10) NOT NULL DEFAULT 'credit',
  date NVARCHAR(40) NOT NULL DEFAULT '',
  reason NVARCHAR(250) NOT NULL DEFAULT '',
  status NVARCHAR(20) NOT NULL DEFAULT 'Completed'
);
CREATE INDEX IX_wallet_user ON wallet_txns(userId);

CREATE TABLE loyalty_activity (
  row INT IDENTITY(1,1) PRIMARY KEY,
  id NVARCHAR(32) NOT NULL,
  userId NVARCHAR(32) NOT NULL,
  name NVARCHAR(160) NOT NULL DEFAULT '',
  meta NVARCHAR(250) NOT NULL DEFAULT '',
  points INT NOT NULL DEFAULT 0
);
CREATE INDEX IX_loyalty_user ON loyalty_activity(userId);

CREATE TABLE recommendations (
  id NVARCHAR(32) PRIMARY KEY,
  title NVARCHAR(200) NOT NULL,
  text NVARCHAR(300) NOT NULL DEFAULT '',
  cta NVARCHAR(80) NOT NULL DEFAULT '',
  providerId NVARCHAR(32) NOT NULL DEFAULT '',
  relevance INT NOT NULL DEFAULT 0,
  basis NVARCHAR(200) NOT NULL DEFAULT ''
);

CREATE TABLE tickets (
  row INT IDENTITY(1,1) PRIMARY KEY,
  id NVARCHAR(32) NOT NULL,
  userId NVARCHAR(32) NOT NULL,
  customerName NVARCHAR(120) NOT NULL DEFAULT '',
  subject NVARCHAR(200) NOT NULL DEFAULT '',
  category NVARCHAR(120) NOT NULL DEFAULT '',
  status NVARCHAR(30) NOT NULL DEFAULT 'In progress',
  priority NVARCHAR(20) NOT NULL DEFAULT 'Medium',
  updated NVARCHAR(60) NOT NULL DEFAULT '',
  messages NVARCHAR(MAX) NOT NULL DEFAULT '[]'
);

CREATE TABLE complaints (
  row INT IDENTITY(1,1) PRIMARY KEY,
  id NVARCHAR(32) NOT NULL,
  title NVARCHAR(200) NOT NULL,
  customer NVARCHAR(120) NOT NULL DEFAULT '',
  channel NVARCHAR(20) NOT NULL DEFAULT 'app',
  priority NVARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  status NVARCHAR(30) NOT NULL DEFAULT 'New',
  age NVARCHAR(40) NOT NULL DEFAULT ''
);

CREATE TABLE jobs (
  id NVARCHAR(32) PRIMARY KEY,
  providerId NVARCHAR(32) NOT NULL,
  kind NVARCHAR(20) NOT NULL DEFAULT 'job',
  customer NVARCHAR(120) NOT NULL DEFAULT '',
  customerMeta NVARCHAR(120) NOT NULL DEFAULT '',
  type NVARCHAR(80) NOT NULL DEFAULT '',
  service NVARCHAR(160) NOT NULL DEFAULT '',
  dateLabel NVARCHAR(40) NOT NULL DEFAULT '',
  timeLabel NVARCHAR(40) NOT NULL DEFAULT '',
  place NVARCHAR(160) NOT NULL DEFAULT '',
  price INT NOT NULL DEFAULT 0,
  status NVARCHAR(20) NOT NULL DEFAULT 'new',
  note NVARCHAR(MAX) NOT NULL DEFAULT '',
  payment NVARCHAR(40) NOT NULL DEFAULT ''
);
CREATE INDEX IX_jobs_provider ON jobs(providerId);

CREATE TABLE availability (
  providerId NVARCHAR(32) PRIMARY KEY,
  [open] BIT NOT NULL DEFAULT 1,
  note NVARCHAR(300) NOT NULL DEFAULT '',
  schedule NVARCHAR(MAX) NOT NULL DEFAULT '[]'
);

CREATE TABLE earnings (
  providerId NVARCHAR(32) PRIMARY KEY,
  week INT NOT NULL DEFAULT 0,
  weekDelta NVARCHAR(80) NOT NULL DEFAULT '',
  pending INT NOT NULL DEFAULT 0,
  pendingNote NVARCHAR(120) NOT NULL DEFAULT '',
  completed INT NOT NULL DEFAULT 0,
  avg INT NOT NULL DEFAULT 0,
  avgNote NVARCHAR(120) NOT NULL DEFAULT '',
  series NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  payments NVARCHAR(MAX) NOT NULL DEFAULT '[]'
);

CREATE TABLE overview (
  id INT PRIMARY KEY,
  metrics NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  series NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  seriesLabels NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  aiInsight NVARCHAR(MAX) NOT NULL DEFAULT '{}',
  topCategory NVARCHAR(MAX) NOT NULL DEFAULT '{}'
);

CREATE TABLE loyalty_admin (
  id INT PRIMARY KEY,
  totals NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  tiers NVARCHAR(MAX) NOT NULL DEFAULT '[]',
  campaign NVARCHAR(MAX) NOT NULL DEFAULT '{}'
);

CREATE TABLE insights (
  tag NVARCHAR(60) PRIMARY KEY,
  title NVARCHAR(300) NOT NULL,
  context NVARCHAR(200) NOT NULL DEFAULT '',
  action NVARCHAR(120) NOT NULL DEFAULT ''
);

CREATE TABLE exports (
  row INT IDENTITY(1,1) PRIMARY KEY,
  id NVARCHAR(32) NOT NULL,
  [by] NVARCHAR(120) NOT NULL DEFAULT '',
  records NVARCHAR(20) NOT NULL DEFAULT '',
  format NVARCHAR(40) NOT NULL DEFAULT '',
  status NVARCHAR(20) NOT NULL DEFAULT 'Completed'
);

CREATE TABLE audit (
  row INT IDENTITY(1,1) PRIMARY KEY,
  at NVARCHAR(60) NOT NULL DEFAULT '',
  [user] NVARCHAR(120) NOT NULL DEFAULT '',
  role NVARCHAR(60) NOT NULL DEFAULT '',
  action NVARCHAR(300) NOT NULL DEFAULT '',
  resource NVARCHAR(60) NOT NULL DEFAULT '',
  result NVARCHAR(20) NOT NULL DEFAULT 'Success'
);
